### ISSUE TITLE
limmbo R package with reticulate

### ISSUE THREAD

**Issue by fboehm** [HannahVMeyer/limmbo#2]
Hi, I hope that it's reasonable for me to post a question here. Have you any plans to make a R wrapper package for your limmbo python module? 

I'm trying to use the R package 'reticulate' to allow for calls to limmbo functions from within an R session. However, I'm running into an error message that, for the moment, I don't fully understand and can't work around. My R code & python code is in a .Rmd file here: https://github.com/fboehm/research-notebook/blob/master/2018-03-21_limmbo-reticulate.Rmd

I posted a stack exchange question on this here: https://stackoverflow.com/questions/49412132/r-python-reticulate-and-limmbo-cast-array-float64-to-int64-error

It seems that the issue I'm encountering is one of conversion between float and integer. The error is:

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: Cannot cast array from dtype('float64') to dtype('int64') according to the rule 'safe'

Detailed traceback: 
  File "/Users/frederickboehm/anaconda2/lib/python2.7/site-packages/limmbo/core/vdbootstrap.py", line 96, in runBootstrapCovarianceEstimation
    minCooccurrence=minCooccurrence)
  File "/Users/frederickboehm/anaconda2/lib/python2.7/site-packages/limmbo/core/vdbootstrap.py", line 353, in __generateBootstrapMatrix
    rand_state = np.random.RandomState(seed)
  File "mtrand.pyx", line 644, in mtrand.RandomState.__init__
  File "mtrand.pyx", line 687, in mtrand.RandomState.seed
Calls: <Anonymous> ... eval -> eval -> <Anonymous> -> py_call_impl ->     .Call

I'm happy to provide any additional information if you might be able to assist me.

Have you seen errors like the one that I'm getting? Do you have any suggestions on what the issue is and how to fix it? 

Thanks!

fred

**Comment by fboehm** [comment]
Please disregard this issue. I created an R package `limmbo2` that serves as a wrapper for limmbo.

**Comment by HannahVMeyer** [comment]
Apologies for my late reply Fred. I have not encountered that issue before, but I am glad you managed to solve it. I've just put a link to your R wrapper for limmbo in the README. Thanks!

**Comment by fboehm** [comment]
Thanks, Hannah! I appreciate the link to the R wrapper.
